services:
  service1:
    build: ./service_1
    networks:
      - dpdzero-net
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
     interval: 30s
     timeout: 10s
     retries: 5
     start_period: 60s
    
  service2:
    build: ./service_2
    networks:
      - dpdzero-net
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
     interval: 30s
     timeout: 10s
     retries: 5
     start_period: 60s

  nginx-proxy:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - service1
      - service2
    networks:
      - dpdzero-net

networks:
  dpdzero-net:
    driver: bridge
